package world_builder;

public class XMLNames
{
	public static String ROOM 			= "room";
	public static String ID				= "id";
	public static String NAME			= "name";
	public static String DESCRIPTION	= "description";
	public static String MOVE			= "move";
	public static String ROOM_ID		= "room_id";
	public static String DIRECTION		= "direction";
	public static String NEXT_ROOM_ID	= "next_room_id";
	public static String OBJECT			= "object";
	public static String DETAIL			= "detail";
	public static String ACTION 		= "action";
	public static String INTRO			= "intro";
	public static String RESULT			= "result";
	public static String TYPE			= "type";
	public static String ITEM_ID		= "item_id";
	public static String VALUE			= "value";
	public static String NPC			= "npc";
	public static String ACTION_RESULTS	= "action_results";
	public static String PARENT			= "parent";
	public static String ITEM			= "item";
	public static String QUEST			= "quest";
	public static String REWARD_XP		= "reward_xp";
	public static String REWARD_GOLD	= "reward_gold";
	public static String REWARD_ITEM	= "reward_item";
	public static String FIRST_BONUS	= "first_bonus";
	public static String QUEST_STEP		= "quest_step";
	public static String HINT			= "hint";
	public static String STEP_NUMBER	= "step_number";
	public static String QUEST_DEP_ID	= "quest_dependency_id";
	public static String QUEST_DEP_STEP	= "quest_dependency_step";
    public static String QUEST_DEP_COMPLETE = "quest_dependency_complete";
    public static String MONSTER        = "monster";
    public static String MONSTER_ID     = "monster_id";
    public static String HEALTH         = "health";
    public static String ATTACK_POWER   = "attack_power";
    public static String MAGIC_POWER    = "magic_power";
    public static String DEFENSE        = "defense";
    public static String MAGIC_DEFENSE  = "magic_defense";
    public static String LOOT_TABLE     = "loot_table_id";
    public static String KILL_XP        = "kill_xp";
    public static String KILL_GOLD      = "kill_gold";
    public static String UPDATE_QUEST_ID    = "update_quest_id";
    public static String UPDATE_QUEST_STEP  = "update_quest_step";
    public static String WEAPON         = "weapon";
    public static String DAMAGE_TYPE    = "damage_type";
    public static String DAMAGE         = "damage";
}
