/* The following code was generated by JFlex 1.4.1 on 11/18/13 11:09 PM */

package minimud_shared;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 11/18/13 11:09 PM from the specification file
 * <tt>./minimud_shared/MessageScanner.jflex</tt>
 */
class MessageScanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\43\1\42\2\0\1\42\22\0\1\43\1\36\1\37\4\36"+
    "\1\35\1\33\1\33\2\36\1\33\2\36\1\27\12\41\1\33\2\36"+
    "\1\34\3\36\32\40\1\36\1\0\2\36\1\4\1\0\1\10\1\32"+
    "\1\26\1\25\1\2\1\11\1\7\1\30\1\22\1\40\1\31\1\15"+
    "\1\5\1\23\1\13\1\14\1\20\1\12\1\6\1\1\1\21\1\17"+
    "\1\24\1\3\1\16\1\40\1\36\1\0\2\36\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\24\0\1\2\2\0\1\1\1\3\3\4\1\5"+
    "\3\4\1\6\7\4\1\7\7\4\1\10\6\4\7\0"+
    "\1\4\1\11\1\12\36\4\10\0\3\4\1\13\1\14"+
    "\1\15\1\16\1\17\1\4\1\20\4\4\1\21\1\4"+
    "\1\22\3\4\1\23\2\4\1\24\1\25\3\4\1\26"+
    "\1\27\1\30\1\31\1\0\1\32\4\0\1\33\2\0"+
    "\1\34\1\4\1\0\2\4\1\35\1\36\1\37\4\4"+
    "\1\40\3\4\1\41\1\4\1\42\5\0\1\43\1\4"+
    "\1\0\1\4\1\44\2\4\1\45\2\4\1\46\1\47"+
    "\1\0\4\4\1\50\4\0\1\4\1\0\1\51\1\0"+
    "\3\4\3\0\1\52\2\4\5\0\1\4\1\53\1\0"+
    "\2\4\4\0\2\4\1\0\1\54\2\0\1\55\1\4"+
    "\1\0\1\56\1\57\4\0\1\60\1\61\1\0\1\62"+
    "\1\0\1\4\6\0\1\63\1\4\6\0\1\4\2\0"+
    "\1\64\1\0\1\65\1\66\1\4\1\67\1\70\1\71"+
    "\23\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[283];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\330\0\374"+
    "\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0\0\u01d4\0\u01f8\0\u021c"+
    "\0\u0240\0\u0264\0\u0288\0\u02ac\0\u02d0\0\u02f4\0\u0318\0\u033c"+
    "\0\u0360\0\u02f4\0\u0384\0\u03a8\0\u03cc\0\u0384\0\u03f0\0\u0414"+
    "\0\u0438\0\u0384\0\u045c\0\u0480\0\u04a4\0\u04c8\0\u04ec\0\u0510"+
    "\0\u0534\0\u0558\0\u057c\0\u05a0\0\u05c4\0\u05e8\0\u060c\0\u0630"+
    "\0\u0654\0\u0384\0\u0678\0\u069c\0\u06c0\0\u06e4\0\u0708\0\u072c"+
    "\0\u0750\0\u0774\0\u0798\0\u07bc\0\u07e0\0\u0804\0\u0828\0\u084c"+
    "\0\u02f4\0\u02f4\0\u0870\0\u0894\0\u08b8\0\u08dc\0\u0900\0\u0924"+
    "\0\u0948\0\u096c\0\u0990\0\u09b4\0\u09d8\0\u09fc\0\u0a20\0\u0a44"+
    "\0\u0a68\0\u0a8c\0\u0ab0\0\u0ad4\0\u0af8\0\u0b1c\0\u0b40\0\u0b64"+
    "\0\u0b88\0\u0bac\0\u0bd0\0\u0bf4\0\u0c18\0\u0c3c\0\u0c60\0\u0c84"+
    "\0\u0ca8\0\u0ccc\0\u0cf0\0\u0d14\0\u0d38\0\u0d5c\0\u0d80\0\u0da4"+
    "\0\u0dc8\0\u0dec\0\u0e10\0\u0dec\0\u0dec\0\u0dec\0\u0dec\0\u0dec"+
    "\0\u0e34\0\u0dec\0\u0e58\0\u0e7c\0\u0ea0\0\u0ec4\0\u0dec\0\u0ee8"+
    "\0\u0dec\0\u0f0c\0\u0f30\0\u0f54\0\u0dec\0\u0f78\0\u0f9c\0\u0dec"+
    "\0\u0dec\0\u0fc0\0\u0fe4\0\u1008\0\u0dec\0\u0dec\0\u0dec\0\u0dec"+
    "\0\u102c\0\u02f4\0\u1050\0\u1074\0\u1098\0\u10bc\0\u02f4\0\u10e0"+
    "\0\u1104\0\u0dec\0\u1128\0\u114c\0\u1170\0\u1194\0\u11b8\0\u1128"+
    "\0\u1128\0\u11dc\0\u1200\0\u1224\0\u1248\0\u1128\0\u126c\0\u1290"+
    "\0\u12b4\0\u12d8\0\u12fc\0\u02f4\0\u1320\0\u1344\0\u1368\0\u138c"+
    "\0\u13b0\0\u02f4\0\u13d4\0\u13f8\0\u141c\0\u1440\0\u1464\0\u1488"+
    "\0\u13d4\0\u14ac\0\u14d0\0\u13d4\0\u13d4\0\u14f4\0\u1518\0\u153c"+
    "\0\u1560\0\u1584\0\u02f4\0\u15a8\0\u15cc\0\u15f0\0\u1614\0\u1638"+
    "\0\u165c\0\u1638\0\u1680\0\u16a4\0\u16c8\0\u16ec\0\u1710\0\u1734"+
    "\0\u1758\0\u1638\0\u177c\0\u17a0\0\u17c4\0\u17e8\0\u180c\0\u1830"+
    "\0\u1854\0\u1878\0\u02f4\0\u189c\0\u18c0\0\u18e4\0\u1908\0\u192c"+
    "\0\u1950\0\u1974\0\u1998\0\u19bc\0\u19e0\0\u02f4\0\u1a04\0\u1a28"+
    "\0\u02f4\0\u1a4c\0\u1a70\0\u1a4c\0\u1a4c\0\u1a94\0\u1ab8\0\u1adc"+
    "\0\u1b00\0\u1a4c\0\u1a4c\0\u1b24\0\u02f4\0\u1b48\0\u1b6c\0\u1b90"+
    "\0\u1bb4\0\u1bd8\0\u1bfc\0\u1c20\0\u1c44\0\u02f4\0\u1c68\0\u1c8c"+
    "\0\u1cb0\0\u1cd4\0\u1cf8\0\u1d1c\0\u1d40\0\u1d64\0\u1d88\0\u1dac"+
    "\0\u02f4\0\u1dd0\0\u02f4\0\u02f4\0\u1df4\0\u02f4\0\u02f4\0\u02f4"+
    "\0\u1e18\0\u1e3c\0\u1e60\0\u1e84\0\u1ea8\0\u1ecc\0\u1ef0\0\u1f14"+
    "\0\u1f38\0\u1f5c\0\u1f80\0\u1fa4\0\u1fc8\0\u1fec\0\u2010\0\u2034"+
    "\0\u2058\0\u207c\0\u02f4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[283];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\0\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\2\13\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\13\1\24\1\13"+
    "\1\25\1\13\2\26\1\27\1\0\1\30\1\13\1\31"+
    "\2\32\1\0\1\33\1\34\1\33\1\0\3\33\1\35"+
    "\2\33\1\36\2\33\1\37\10\33\1\0\3\33\5\0"+
    "\2\33\3\0\2\33\1\40\1\0\3\33\1\41\16\33"+
    "\1\0\3\33\5\0\2\33\3\0\3\33\1\0\7\33"+
    "\1\42\12\33\1\0\3\33\5\0\2\33\3\0\1\33"+
    "\1\43\1\33\1\0\22\33\1\0\3\33\5\0\2\33"+
    "\3\0\1\44\1\45\1\33\1\0\6\33\1\46\1\33"+
    "\1\47\11\33\1\0\1\50\2\33\5\0\2\33\3\0"+
    "\3\33\1\0\6\33\1\51\13\33\1\0\3\33\5\0"+
    "\2\33\3\0\1\52\2\33\1\0\22\33\1\0\3\33"+
    "\5\0\2\33\3\0\3\33\1\0\5\33\1\53\14\33"+
    "\1\0\3\33\5\0\2\33\3\0\1\33\1\54\1\33"+
    "\1\0\22\33\1\0\3\33\5\0\2\33\3\0\3\33"+
    "\1\0\22\33\1\0\3\33\5\0\2\33\3\0\3\33"+
    "\1\0\3\33\1\55\4\33\1\56\3\33\1\57\5\33"+
    "\1\0\3\33\5\0\2\33\3\0\3\33\1\0\6\33"+
    "\1\60\13\33\1\0\3\33\5\0\2\33\3\0\3\33"+
    "\1\0\14\33\1\61\5\33\1\0\3\33\5\0\2\33"+
    "\3\0\3\33\1\0\7\33\1\62\12\33\1\0\3\33"+
    "\5\0\2\33\3\0\3\33\1\0\16\33\1\63\3\33"+
    "\1\0\3\33\5\0\2\33\3\0\3\33\1\0\6\33"+
    "\1\64\13\33\1\0\3\33\5\0\2\33\3\0\1\33"+
    "\1\65\1\33\1\0\15\33\1\66\4\33\1\0\3\33"+
    "\5\0\2\33\3\0\3\33\1\0\5\33\1\67\1\70"+
    "\13\33\1\0\3\33\5\0\2\33\3\0\1\71\4\0"+
    "\1\72\6\0\1\73\2\0\1\74\1\0\1\75\1\0"+
    "\1\76\3\0\1\77\14\0\3\33\1\0\15\33\1\100"+
    "\4\33\1\0\3\33\5\0\2\33\47\0\33\27\1\0"+
    "\1\101\4\27\1\0\1\27\1\0\33\30\1\0\2\30"+
    "\1\102\2\30\1\0\1\30\41\0\1\31\3\0\3\103"+
    "\1\0\22\103\1\0\3\103\5\0\2\103\3\0\2\103"+
    "\1\104\1\0\22\103\1\0\3\103\5\0\2\103\3\0"+
    "\3\103\1\0\10\103\1\105\11\103\1\0\1\103\1\106"+
    "\1\103\5\0\2\103\3\0\3\103\1\0\7\103\1\107"+
    "\12\103\1\0\3\103\5\0\2\103\3\0\3\103\1\0"+
    "\15\103\1\110\4\103\1\0\3\103\5\0\2\103\3\0"+
    "\3\103\1\0\1\103\1\111\20\103\1\0\3\103\5\0"+
    "\2\103\3\0\3\103\1\0\1\103\1\112\20\103\1\0"+
    "\3\103\5\0\2\103\3\0\3\103\1\0\3\103\1\113"+
    "\16\103\1\0\3\103\5\0\2\103\3\0\3\103\1\0"+
    "\5\103\1\114\14\103\1\0\3\103\5\0\2\103\3\0"+
    "\3\103\1\0\14\103\1\115\5\103\1\0\3\103\5\0"+
    "\2\103\3\0\3\103\1\0\3\103\1\116\16\103\1\0"+
    "\3\103\5\0\2\103\3\0\3\103\1\0\6\103\1\117"+
    "\13\103\1\0\3\103\5\0\2\103\3\0\3\103\1\0"+
    "\10\103\1\120\11\103\1\0\3\103\5\0\2\103\3\0"+
    "\1\121\2\103\1\0\22\103\1\0\3\103\5\0\2\103"+
    "\3\0\3\103\1\0\6\103\1\122\13\103\1\0\3\103"+
    "\5\0\2\103\3\0\3\103\1\0\13\103\1\123\6\103"+
    "\1\0\3\103\5\0\2\103\3\0\3\103\1\0\1\103"+
    "\1\124\20\103\1\0\3\103\5\0\2\103\3\0\3\103"+
    "\1\0\3\103\1\125\16\103\1\0\3\103\5\0\2\103"+
    "\3\0\3\103\1\0\1\103\1\126\14\103\1\127\3\103"+
    "\1\0\3\103\5\0\2\103\3\0\3\103\1\0\2\103"+
    "\1\130\3\103\1\131\13\103\1\0\3\103\5\0\2\103"+
    "\3\0\3\103\1\0\15\103\1\132\4\103\1\0\3\103"+
    "\5\0\2\103\3\0\3\103\1\0\12\103\1\133\7\103"+
    "\1\0\3\103\5\0\2\103\3\0\3\103\1\0\5\103"+
    "\1\134\14\103\1\0\3\103\5\0\2\103\3\0\3\103"+
    "\1\0\1\103\1\135\20\103\1\0\3\103\5\0\2\103"+
    "\3\0\1\136\2\103\1\0\22\103\1\0\3\103\5\0"+
    "\2\103\3\0\3\103\1\0\6\103\1\137\13\103\1\0"+
    "\3\103\5\0\2\103\3\0\3\103\1\0\17\103\1\140"+
    "\2\103\1\0\3\103\5\0\2\103\4\0\1\141\51\0"+
    "\1\142\17\0\1\143\15\0\1\144\62\0\1\145\45\0"+
    "\1\146\50\0\1\147\15\0\1\150\42\0\3\103\1\0"+
    "\21\103\1\151\1\0\3\103\5\0\2\103\3\0\3\152"+
    "\1\0\22\152\1\0\3\152\5\0\2\152\3\0\1\153"+
    "\2\152\1\0\22\152\1\0\3\152\5\0\2\152\3\0"+
    "\3\152\1\0\22\152\1\0\1\152\1\154\1\152\5\0"+
    "\2\152\3\0\1\152\1\155\1\152\1\0\22\152\1\0"+
    "\3\152\5\0\2\152\3\0\1\152\1\156\1\152\1\0"+
    "\22\152\1\0\3\152\5\0\2\152\3\0\1\157\2\152"+
    "\1\0\22\152\1\0\3\152\5\0\2\152\3\0\1\160"+
    "\2\152\1\0\22\152\1\0\3\152\5\0\2\152\3\0"+
    "\3\152\1\0\1\152\1\161\20\152\1\0\3\152\5\0"+
    "\2\152\3\0\3\152\1\0\22\152\1\0\2\152\1\162"+
    "\5\0\2\152\3\0\3\152\1\0\12\152\1\163\7\152"+
    "\1\0\3\152\5\0\2\152\3\0\1\164\2\152\1\0"+
    "\22\152\1\0\3\152\5\0\2\152\3\0\3\152\1\0"+
    "\1\152\1\165\20\152\1\0\3\152\5\0\2\152\3\0"+
    "\3\152\1\0\6\152\1\166\13\152\1\0\3\152\5\0"+
    "\2\152\3\0\3\152\1\0\20\152\1\167\1\152\1\0"+
    "\3\152\5\0\2\152\3\0\3\152\1\0\3\152\1\170"+
    "\16\152\1\0\3\152\5\0\2\152\3\0\3\152\1\0"+
    "\1\171\21\152\1\0\3\152\5\0\2\152\3\0\3\152"+
    "\1\0\14\152\1\172\5\152\1\0\3\152\5\0\2\152"+
    "\3\0\3\152\1\0\1\152\1\173\20\152\1\0\3\152"+
    "\5\0\2\152\3\0\3\152\1\0\11\152\1\174\10\152"+
    "\1\0\3\152\5\0\2\152\3\0\3\152\1\0\22\152"+
    "\1\0\1\175\2\152\5\0\2\152\3\0\3\152\1\0"+
    "\21\152\1\176\1\0\3\152\5\0\2\152\3\0\3\152"+
    "\1\0\6\152\1\177\13\152\1\0\3\152\5\0\2\152"+
    "\3\0\3\152\1\0\22\152\1\0\1\152\1\200\1\152"+
    "\5\0\2\152\3\0\1\201\2\152\1\0\22\152\1\0"+
    "\3\152\5\0\2\152\3\0\3\152\1\0\3\152\1\202"+
    "\16\152\1\0\3\152\5\0\2\152\3\0\1\203\2\152"+
    "\1\0\1\204\21\152\1\0\3\152\5\0\2\152\3\0"+
    "\1\205\2\152\1\0\22\152\1\0\3\152\5\0\2\152"+
    "\3\0\3\152\1\0\22\152\1\0\1\206\2\152\5\0"+
    "\2\152\3\0\3\152\1\0\7\152\1\207\12\152\1\0"+
    "\3\152\5\0\2\152\3\0\3\152\1\0\16\152\1\210"+
    "\3\152\1\0\3\152\5\0\2\152\17\0\1\211\44\0"+
    "\1\212\40\0\1\213\40\0\1\214\35\0\1\215\60\0"+
    "\1\216\37\0\1\217\6\0\1\220\36\0\1\221\27\0"+
    "\3\152\1\0\22\152\1\0\1\152\1\222\1\152\5\0"+
    "\2\152\3\0\3\223\1\0\22\223\1\0\3\223\5\0"+
    "\2\223\3\0\3\223\1\224\22\223\1\0\3\223\5\0"+
    "\2\223\3\0\3\223\1\0\3\223\1\225\16\223\1\0"+
    "\3\223\5\0\2\223\3\0\1\223\1\226\1\223\1\0"+
    "\22\223\1\0\3\223\5\0\2\223\3\0\3\223\1\0"+
    "\22\223\1\0\1\227\2\223\5\0\2\223\3\0\3\223"+
    "\1\0\22\223\1\0\1\230\2\223\5\0\2\223\3\0"+
    "\1\231\2\223\1\0\22\223\1\0\3\223\5\0\2\223"+
    "\3\0\3\223\1\0\21\223\1\232\1\0\3\223\5\0"+
    "\2\223\3\0\1\223\1\233\1\223\1\0\22\223\1\0"+
    "\3\223\5\0\2\223\3\0\3\223\1\0\17\223\1\234"+
    "\2\223\1\0\3\223\5\0\2\223\3\0\1\223\1\235"+
    "\1\223\1\0\22\223\1\0\3\223\5\0\2\223\3\0"+
    "\3\223\1\0\22\223\1\0\1\236\2\223\5\0\2\223"+
    "\3\0\3\223\1\0\14\223\1\237\1\223\1\240\3\223"+
    "\1\0\3\223\5\0\2\223\3\0\3\223\1\0\10\223"+
    "\1\241\11\223\1\0\3\223\5\0\2\223\3\0\3\223"+
    "\1\0\22\223\1\0\1\242\2\223\5\0\2\223\3\0"+
    "\3\223\1\0\3\223\1\243\16\223\1\0\3\223\5\0"+
    "\2\223\17\0\1\244\47\0\1\245\47\0\1\246\24\0"+
    "\1\247\37\0\1\250\47\0\1\251\51\0\1\252\30\0"+
    "\3\253\1\0\22\253\1\0\3\253\5\0\2\253\7\0"+
    "\1\254\37\0\3\253\1\0\2\253\1\255\17\253\1\0"+
    "\3\253\5\0\2\253\3\0\3\253\1\0\5\253\1\256"+
    "\14\253\1\0\3\253\5\0\2\253\3\0\1\253\1\257"+
    "\1\253\1\0\17\253\1\260\2\253\1\0\3\253\5\0"+
    "\2\253\3\0\3\253\1\0\22\253\1\0\1\253\1\261"+
    "\1\253\5\0\2\253\3\0\3\253\1\0\1\253\1\262"+
    "\20\253\1\0\3\253\5\0\2\253\3\0\3\253\1\0"+
    "\20\253\1\263\1\253\1\0\3\253\5\0\2\253\3\0"+
    "\3\253\1\0\5\253\1\264\14\253\1\0\3\253\5\0"+
    "\2\253\3\0\1\265\2\253\1\0\22\253\1\0\3\253"+
    "\5\0\2\253\3\0\3\253\1\266\22\253\1\0\3\253"+
    "\5\0\2\253\3\0\3\253\1\0\15\253\1\267\4\253"+
    "\1\0\3\253\5\0\2\253\3\0\1\253\1\270\1\253"+
    "\1\0\17\253\1\271\2\253\1\0\3\253\5\0\2\253"+
    "\3\0\3\253\1\0\10\253\1\272\11\253\1\0\3\253"+
    "\5\0\2\253\3\0\1\273\44\0\1\274\42\0\1\275"+
    "\65\0\1\276\34\0\1\277\30\0\3\300\1\0\22\300"+
    "\1\0\3\300\5\0\2\300\10\0\1\301\36\0\1\300"+
    "\1\302\1\300\1\0\22\300\1\0\3\300\5\0\2\300"+
    "\3\0\3\300\1\303\22\300\1\0\3\300\5\0\2\300"+
    "\3\0\3\300\1\0\3\300\1\304\16\300\1\0\3\300"+
    "\5\0\2\300\3\0\1\300\1\305\1\300\1\0\22\300"+
    "\1\0\3\300\5\0\2\300\3\0\1\306\2\300\1\0"+
    "\22\300\1\0\3\300\5\0\2\300\3\0\3\300\1\307"+
    "\22\300\1\0\3\300\5\0\2\300\10\0\1\310\2\0"+
    "\1\311\33\0\3\300\1\0\20\300\1\312\1\300\1\0"+
    "\3\300\5\0\2\300\3\0\3\300\1\0\3\300\1\313"+
    "\16\300\1\0\3\300\5\0\2\300\3\0\1\300\1\314"+
    "\1\300\1\0\22\300\1\0\3\300\5\0\2\300\3\0"+
    "\3\300\1\315\22\300\1\0\3\300\5\0\2\300\14\0"+
    "\1\316\46\0\1\317\27\0\1\320\44\0\1\321\42\0"+
    "\3\322\1\0\22\322\1\0\3\322\5\0\2\322\11\0"+
    "\1\323\42\0\1\324\36\0\3\322\1\0\1\322\1\325"+
    "\20\322\1\0\3\322\5\0\2\322\3\0\3\322\1\0"+
    "\1\322\1\326\20\322\1\0\3\322\5\0\2\322\3\0"+
    "\3\322\1\327\22\322\1\0\3\322\5\0\2\322\24\0"+
    "\1\330\42\0\1\331\32\0\1\332\34\0\3\322\1\0"+
    "\1\322\1\333\20\322\1\0\3\322\5\0\2\322\3\0"+
    "\3\322\1\0\1\322\1\334\20\322\1\0\3\322\5\0"+
    "\2\322\24\0\1\335\27\0\1\336\50\0\1\337\43\0"+
    "\1\340\42\0\1\341\32\0\3\342\1\0\22\342\1\0"+
    "\3\342\5\0\2\342\3\0\1\343\43\0\1\344\2\342"+
    "\1\0\22\342\1\0\3\342\5\0\2\342\3\0\1\345"+
    "\2\342\1\0\22\342\1\0\3\342\5\0\2\342\24\0"+
    "\1\346\44\0\1\347\46\0\1\350\37\0\1\351\22\0"+
    "\1\352\2\342\1\0\22\342\1\0\3\342\5\0\2\342"+
    "\3\0\1\353\2\342\1\0\22\342\1\0\3\342\5\0"+
    "\2\342\25\0\1\354\27\0\1\355\46\0\1\356\32\0"+
    "\3\357\1\0\22\357\1\0\3\357\5\0\2\357\12\0"+
    "\1\360\56\0\1\361\34\0\1\362\55\0\1\363\32\0"+
    "\1\364\42\0\1\365\45\0\1\366\26\0\3\367\1\0"+
    "\22\367\1\0\3\367\5\0\2\367\3\0\1\370\56\0"+
    "\1\371\50\0\1\372\24\0\1\373\43\0\1\374\62\0"+
    "\1\375\23\0\3\376\1\0\22\376\1\0\3\376\5\0"+
    "\2\376\23\0\1\377\43\0\1\u0100\23\0\1\u0101\50\0"+
    "\1\u0102\62\0\1\u0103\17\0\1\u0104\43\0\3\u0105\1\0"+
    "\22\u0105\1\0\3\u0105\5\0\2\u0105\10\0\1\u0106\36\0"+
    "\1\u0107\50\0\1\u0108\36\0\3\u0109\1\0\22\u0109\1\0"+
    "\3\u0109\5\0\2\u0109\3\0\3\u010a\1\0\22\u010a\1\0"+
    "\3\u010a\5\0\2\u010a\3\0\3\u010b\1\0\22\u010b\1\0"+
    "\3\u010b\5\0\2\u010b\3\0\3\u010c\1\0\22\u010c\1\0"+
    "\3\u010c\5\0\2\u010c\3\0\3\u010d\1\0\22\u010d\1\0"+
    "\3\u010d\5\0\2\u010d\3\0\3\u010e\1\0\22\u010e\1\0"+
    "\3\u010e\5\0\2\u010e\3\0\3\u010f\1\0\22\u010f\1\0"+
    "\3\u010f\5\0\2\u010f\3\0\3\u0110\1\0\22\u0110\1\0"+
    "\3\u0110\5\0\2\u0110\3\0\3\u0111\1\0\22\u0111\1\0"+
    "\3\u0111\5\0\2\u0111\3\0\3\u0112\1\0\22\u0112\1\0"+
    "\3\u0112\5\0\2\u0112\3\0\3\u0113\1\0\22\u0113\1\0"+
    "\3\u0113\5\0\2\u0113\3\0\3\u0114\1\0\22\u0114\1\0"+
    "\3\u0114\5\0\2\u0114\3\0\3\u0115\1\0\22\u0115\1\0"+
    "\3\u0115\5\0\2\u0115\3\0\3\u0116\1\0\22\u0116\1\0"+
    "\3\u0116\5\0\2\u0116\3\0\3\u0117\1\0\22\u0117\1\0"+
    "\3\u0117\5\0\2\u0117\3\0\3\u0118\1\0\22\u0118\1\0"+
    "\3\u0118\5\0\2\u0118\3\0\3\u0119\1\0\22\u0119\1\0"+
    "\3\u0119\5\0\2\u0119\3\0\3\u011a\1\0\22\u011a\1\0"+
    "\3\u011a\5\0\2\u011a\3\0\3\u011b\1\0\22\u011b\1\0"+
    "\3\u011b\5\0\2\u011b\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8352];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\24\0\1\11\2\0\1\1\1\11\36\1\7\0"+
    "\1\1\2\11\36\1\10\0\40\1\1\0\1\11\4\0"+
    "\1\11\2\0\2\1\1\0\17\1\1\11\5\0\1\11"+
    "\1\1\1\0\11\1\1\0\4\1\1\11\4\0\1\1"+
    "\1\0\1\1\1\0\3\1\3\0\3\1\5\0\1\1"+
    "\1\11\1\0\2\1\4\0\2\1\1\0\1\11\2\0"+
    "\1\11\1\1\1\0\2\1\4\0\2\1\1\0\1\11"+
    "\1\0\1\1\6\0\1\11\1\1\6\0\1\1\2\0"+
    "\1\11\1\0\2\11\1\1\3\11\22\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[283];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

/* store a reference to the parser object */
	private MessageParser yyparser;

	/* constructor taking an additional parser */
	public MessageScanner (java.io.Reader r, MessageParser yyparser) {
		this (r);	
		this.yyparser = yyparser;
	}

	/* return the current line number. We need this
	   because yyline is made private and we don't have
	   a mechanism like extern in C. */
	public int getLine() {
		return yyline;
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  MessageScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  MessageScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 116) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 47: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.GO_SOUTHWEST;
          }
        case 58: break;
        case 10: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.STRINGLITERAL;
          }
        case 59: break;
        case 27: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.WHO;
          }
        case 60: break;
        case 48: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.GO_NORTHEAST;
          }
        case 61: break;
        case 32: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.PUNCH;
          }
        case 62: break;
        case 44: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.LEADERS;
          }
        case 63: break;
        case 36: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.SERVER;
          }
        case 64: break;
        case 14: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.EXIT;
          }
        case 65: break;
        case 51: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.INVENTORY;
          }
        case 66: break;
        case 37: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.ATTACK;
          }
        case 67: break;
        case 5: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.TO;
          }
        case 68: break;
        case 11: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.TALK;
          }
        case 69: break;
        case 12: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.TAKE;
          }
        case 70: break;
        case 31: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.SHOOT;
          }
        case 71: break;
        case 43: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.TEXTMSG;
          }
        case 72: break;
        case 46: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.GO_SOUTHEAST;
          }
        case 73: break;
        case 45: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.WHISPER;
          }
        case 74: break;
        case 42: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.INVALID;
          }
        case 75: break;
        case 8: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.GO_UP;
          }
        case 76: break;
        case 3: 
          { ;
          }
        case 77: break;
        case 6: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.XP;
          }
        case 78: break;
        case 25: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.GO_DOWN;
          }
        case 79: break;
        case 29: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.GO_SOUTH;
          }
        case 80: break;
        case 4: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.CHARNAME;
          }
        case 81: break;
        case 16: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.STAB;
          }
        case 82: break;
        case 53: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.LOGON_FAILED;
          }
        case 83: break;
        case 35: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.HELP;
          }
        case 84: break;
        case 34: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.TELL;
          }
        case 85: break;
        case 56: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.REQUEST_INPUT;
          }
        case 86: break;
        case 13: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.TYPE;
          }
        case 87: break;
        case 41: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.MESSAGE;
          }
        case 88: break;
        case 24: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.DROP;
          }
        case 89: break;
        case 33: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.GO_NORTH;
          }
        case 90: break;
        case 22: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.GO_WEST;
          }
        case 91: break;
        case 40: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.SHOUT;
          }
        case 92: break;
        case 38: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.PLAYER;
          }
        case 93: break;
        case 21: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.QUIT;
          }
        case 94: break;
        case 54: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.NORMAL_INPUT;
          }
        case 95: break;
        case 19: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.PUSH;
          }
        case 96: break;
        case 23: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.WITH;
          }
        case 97: break;
        case 7: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.AT;
          }
        case 98: break;
        case 49: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.GO_NORTHWEST;
          }
        case 99: break;
        case 20: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.LOOK;
          }
        case 100: break;
        case 17: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.GOLD;
          }
        case 101: break;
        case 9: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.CHARLITERAL;
          }
        case 102: break;
        case 55: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.SERVER_STATUS;
          }
        case 103: break;
        case 15: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.GO_EAST;
          }
        case 104: break;
        case 39: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.LOGOUT;
          }
        case 105: break;
        case 30: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.SLASH;
          }
        case 106: break;
        case 50: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.QUESTLOG;
          }
        case 107: break;
        case 52: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.PASSWD_INPUT;
          }
        case 108: break;
        case 26: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.SAY;
          }
        case 109: break;
        case 1: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.INT;
          }
        case 110: break;
        case 28: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.KICK;
          }
        case 111: break;
        case 57: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.LOGON_SUCCESS;
          }
        case 112: break;
        case 2: 
          { return (int)yycharat(0);
          }
        case 113: break;
        case 18: 
          { yyparser.yylval = new MessageParserVal(yytext()); return MessageParser.FROM;
          }
        case 114: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
